## Liner Algebra for Data Science

- Machine Learning
Regression Analysis:Linear Algbera is the fundamental to linear regression to find the best fit into the data points. The co-efficient of regression equation are determine using matrix operation

Principal component analysis: PCA is extensively used in ML models for dimensional reduction.It involves finding eigen values and eigen vectors of covarience matrix

## Eigen Values and eigen vectors
a) they are fundamental concepts in linear algebra with wide range of applications in various feild including data science ml models

b) They reprresent the scaling by which an eigen vector is streched or compressed when linear tranformation applied

- Super vector machine (SVM): it involve system of equations to find 

1) neural network 
- system equation

2) Backprogation

3) computer vision
Image processing - linear transformation

homography - used linear for in computer vision to find transformation

4) Natural Language Processing (NLP)
- word embeding
- matrix factorization

5) Statistics and Data Analysis
- covariance and corelation
- multivarient analysis

6) Optimization
- finding global max, local max and gradient descent/Linear programming

7) Network analysis




Deep knowledge of
ML engineer - Intermediate

Machine learning scientist - expert (phd in math and software engineers)

Algorthim developer - Intermediate

principal data scientist - Intermediate

Data Scientist - basic and beyond

engineers - very basic

MLOPs - very basic who deploying trained ml models, moniter and track the performance

In [1]:
#vectors and scalars

import numpy as np

# vectors and arrays of numbers
# Scalar are singular numeric values

vectors = np.array([1,2,3])
scalar = 5

In [ ]:
# matrix
# is a 2d array of numbers

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

matrix

In [3]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [ ]:
# addition

A+B

In [5]:
#scalar multiplication
2*A

array([[2, 4],
       [6, 8]])

In [6]:
# Matrix Multiplication

E = np.dot(A, B) #dot is numpy inbuilt function

In [7]:
E

array([[19, 22],
       [43, 50]])

In [8]:
# Matrix transpose
# flip of matrix its rows and columns
f = np.transpose(A)

In [12]:
f

array([[1, 3],
       [2, 4]])

In [9]:
# matrix Inversion
# The inverse of a square matrix A, denoted as A ^(-1), allows solving equations of 
#Ax = b

In [10]:
from numpy.linalg import inv

A_inv = inv(A)

In [11]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
#Determines
#Used to check singular for a given system of equation has solution or not

In [ ]:
# Eigen values and Eigen vector - Data Dimensionality reduction

In [ ]:
#Solving Linear equation

In [ ]:
#martix Decomposition

#Important for data analysis tasks